modLoader = "javafml"
loaderVersion = "${mod_neo_loader_version}"
issueTrackerURL = "${mod_sources}"
license = "LGPLv3"
logoFile = "${logo_file}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
displayURL="${mod_website}"

[[dependencies.compact_storage]]
modId = "neoforge"
type = "required"
versionRange = "${mod_neo_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.compact_storage]]
modId = "minecraft"
type = "required"
versionRange = "${mod_neo_minecraft_range}"
ordering = "NONE"
side = "BOTH"